/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MesRestaurantsRouteImport } from './routes/mes-restaurants'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as AvisIdRouteImport } from './routes/avis.$id'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'
import { Route as VoteIndexRouteImport } from './routes/vote.index'
import { Route as VoteSessionIdRouteImport } from './routes/vote.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesRestaurantsRoute = MesRestaurantsRouteImport.update({
  id: '/mes-restaurants',
  path: '/mes-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisIdRoute = AvisIdRouteImport.update({
  id: '/avis/$id',
  path: '/avis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteIndexRoute = VoteIndexRouteImport.update({
  id: '/vote/',
  path: '/vote/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteSessionIdRoute = VoteSessionIdRouteImport.update({
  id: '/vote/$sessionId',
  path: '/vote/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mes-restaurants': typeof MesRestaurantsRoute
  '/profil': typeof ProfilRoute
  '/avis/$id': typeof AvisIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/vote/$sessionId': typeof VoteSessionIdRoute
  '/vote/': typeof VoteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mes-restaurants': typeof MesRestaurantsRoute
  '/profil': typeof ProfilRoute
  '/avis/$id': typeof AvisIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/vote/$sessionId': typeof VoteSessionIdRoute
  '/vote': typeof VoteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mes-restaurants': typeof MesRestaurantsRoute
  '/profil': typeof ProfilRoute
  '/avis/$id': typeof AvisIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/vote/$sessionId': typeof VoteSessionIdRoute
  '/vote/': typeof VoteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mes-restaurants'
    | '/profil'
    | '/avis/$id'
    | '/restaurant/$id'
    | '/vote/$sessionId'
    | '/vote/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mes-restaurants'
    | '/profil'
    | '/avis/$id'
    | '/restaurant/$id'
    | '/vote/$sessionId'
    | '/vote'
  id:
    | '__root__'
    | '/'
    | '/mes-restaurants'
    | '/profil'
    | '/avis/$id'
    | '/restaurant/$id'
    | '/vote/$sessionId'
    | '/vote/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MesRestaurantsRoute: typeof MesRestaurantsRoute
  ProfilRoute: typeof ProfilRoute
  AvisIdRoute: typeof AvisIdRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
  VoteSessionIdRoute: typeof VoteSessionIdRoute
  VoteIndexRoute: typeof VoteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-restaurants': {
      id: '/mes-restaurants'
      path: '/mes-restaurants'
      fullPath: '/mes-restaurants'
      preLoaderRoute: typeof MesRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis/$id': {
      id: '/avis/$id'
      path: '/avis/$id'
      fullPath: '/avis/$id'
      preLoaderRoute: typeof AvisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/': {
      id: '/vote/'
      path: '/vote'
      fullPath: '/vote/'
      preLoaderRoute: typeof VoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$sessionId': {
      id: '/vote/$sessionId'
      path: '/vote/$sessionId'
      fullPath: '/vote/$sessionId'
      preLoaderRoute: typeof VoteSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MesRestaurantsRoute: MesRestaurantsRoute,
  ProfilRoute: ProfilRoute,
  AvisIdRoute: AvisIdRoute,
  RestaurantIdRoute: RestaurantIdRoute,
  VoteSessionIdRoute: VoteSessionIdRoute,
  VoteIndexRoute: VoteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
